### ISSUE TITLE
tqdm not mentioned as a dependency

### ISSUE THREAD

**Issue by swwalsh** [vkola-lab/DREAMER#2]
Hi there,
The 'tdqm' package is used in DREAMER.py but is not mentioned as a dependency. Line 27 of DREAMER.py:
```
from tqdm import tqdm
```

Running DREAMER.py without it installed leads to error messages:|
```
$ python DREAMER_Run.py 
Traceback (most recent call last):
  File "/autofs/vast/neuromod/2023Temp/shane_walsh/DREAMER/eeg_tests/DREAMER_Run.py", line 7, in <module>
    from DREAMER import DREAMER
  File "/autofs/vast/neuromod/2023Temp/shane_walsh/DREAMER/DREAMER/DREAMER.py", line 27, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

```
Thanks

**Comment by me-ahangaran** [comment]
The issue was resolved.
Thanks.

**Comment by me-ahangaran** [comment]
Issue was resolved.
